spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none # update 模型更改不会更新， none create-drop
  jackson:
    property-naming-strategy: SNAKE_CASE # 返回数据key 为下划线形式
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true # 设置返回时间格式
  logging:
    level:
      # web信息日志记录
      web: debug
      # SQL日志记录
      com.fui.fuistore.mapper: debug

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 指定默认枚举类型的类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    # 开启/关闭 banner 打印
    banner: true
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml

fuiStore:
  api-package: com.fui.fuistore.api

